### ISSUE TITLE
Questions on usage.

### ISSUE THREAD

**Issue by lauhakari** [kavalcante/vue-truncate-collapsed#2]
Hey, first of - great plugin! Did exactly what I needed and nothing more.

I have a few questions on usage though, as I got some weird cases in some situations.
Firstly: using _text=""_ doesn't work if you pass data to it. You need to use _:text=""_ , maybe this could be made clear in the docs :)

Second: I encountered this error in some cases with _length="250"_ .
```[Vue warn]: Invalid prop: type check failed for prop "length". Expected Number, got String.```
Really pulled my hair on this one as it hade worked just the day before. Ended up trying _:length="250"_ and it worked fine.

So maybe they all should be added as _:propName=""_ instead of _propName=""_

**Comment by congtoanle** [comment]
Are you use SSR or Nuxt, right

**Comment by kavalcante** [comment]
Hello @lauhakari thanks for you issue.

First: This is weird, because it's should work if you just do text="lorem ipsum", because it's a valid String, if is possible you can reproduce the error?

Second: Thanks for this, in Attributes I put that it's only accept Number, but in Usage I'm using a String, I will fix that in the docs!
